# Generated by Django 4.2.7 on 2024-01-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_purchased_by_buycar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyCar',
        ),
    ]
